name: repo-events
on: [push, pull_request, issues]
jobs:
  handle-repo-events:
    runs-on: ubuntu-latest
    steps:
    - name: Log event information   
      run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Sender: ${{ github.actor }}"
          echo "short SHA: $GITHUB_SHA"
          echo "short REF: $GITHUB_REF"
    - uses: actions/checkout@v3
